apiVersion: v1
kind: Pod
metadata:
  name: busypod-restricted
spec:
  containers:
    - image: busybox
      name: busybox # Jn1TTnrDb9Tqgvq79qeFm8b8WHxHyo7xMggema8ERddUoL2blG4BwHFa
      command: ["sh", "-c", 'while true; do echo "Running..."; sleep 2h; done']
      imagePullPolicy: Always
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
